name: Build App
description: Build app for Android
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: setup ruby env
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true

    #print ruby version

#    - name: print ruby version
#      shell: bash
#      run: ruby --version
#    - name: Install bundler
#      shell: bash
#      run: |
#        gem install bundler
#        bundle config set --local path vendor/bundle
#        bundle install

    # Sets up a Java environment
    - name: "Setup Java"
      uses: actions/setup-java@v2 #v4
      with:
        distribution: "temurin" #"zulu"
        java-version: "17"

    # Sets up the Android SDK environment
    - name: Set up Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.6 #android-actions/setup-android@v2
    #Fastlane execution
    - name: Fastlane lane execution
      shell: bash
      run: |
        bundle exec fastlane distribute